import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Videobutton from '../components/videobutton'

import dynamic from "next/dynamic";
import Link from 'next/link'
const ReactPlayer = dynamic(() => import("react-player/lazy"), { ssr: false });

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <Videobutton link={"/Push"} content={"Push Exercises"}></Videobutton>
      <Videobutton link={"/Task"} content={"Task Exercises"}></Videobutton>
      <Videobutton link={"/videos/sittostand_beginner"} content={"Program Info"}></Videobutton>
      
      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
